### ISSUE TITLE
2 Errors when running test cases.

### ISSUE THREAD

**Issue by AdityaGupta03** [SPFresh/SPFresh#11]
Hi, when running the test case executable that is created on build (./Release/SPTAGTest), I get the following two errors. Is this a known issue or is the error on my end? Thanks!

/home/azureuser/SPFresh/Test/src/AlgoTest.cpp(45): error: in "AlgoTest/SPANNTest": check SPTAG::ErrorCode::Success == vecIndex->SaveIndex(out) has failed
unknown location(0): fatal error: in "AlgoTest/SPANNTest": memory access violation at address: 0x00000000: no mapping at fault address
/home/azureuser/SPFresh/Test/src/AlgoTest.cpp(45): last checkpoint
*** 2 failures are detected in the test module "Main"

**Comment by Yuming-Xu** [comment]
Hi, ./Release/SPTAGTest is unelectable. Since this repo is just for artifact evaluation, we didn't make any modification for the test case, we only focus on the experiment run by /Release/spfresh
We are merging the SPFresh code into SPTAG repo, where we will consider to make it consistent with the test cases:)

**Comment by AdityaGupta03** [comment]
Great, thanks for your help!
