### ISSUE TITLE
Question about truthpath parameter definition

### ISSUE THREAD

**Issue by Funlxy** [SPFresh/SPFresh#4]
In the file `generateOverallPerformanceTraceAndTruth.sh`.
You use the following command:
`sed -i "$newtruthname" genTruth.ini` to change the value of the TruthPath parameter.
Did you forget to add `$i` ?  For example, you should add a statement like this: `newtruthname=$truthname$i`, otherwise it won't change with the change of `i`.

Another problem is that you are using the following parameters to generate ConvertTruth：
` /home/sosp/SPFresh/Release/usefultool -ConvertTruth true .............`
But you seem to have forgotten to add the `--truthPath` parameter, which specifies the location of the truthfile,so it won't be able to read the truthfile correctly.
And this parameter should be specified as `--truthPath spacev100m_update_truth`, then it can be loaded correctly by the ConvertTruth function in usefultool:
![](https://typora-picgo-picbed.oss-cn-shenzhen.aliyuncs.com/img/20231209154304.png)

**Comment by Funlxy** [comment]
you also forget --resultNum 10 --querySize 29316

**Comment by Yuming-Xu** [comment]
Oh we did forget to add those parameters in the shell script since we didn't fully test the generation script in this AE repo (we use other scripts in our experiments to generate data and we try to merge code within the repo during AE) :(

Your analysis is correct and we will fix this script as soon as possible.

If you are in a hurry, I suggest you to fix this script in yourself, the logic is easy:

Generate trace based on the current system vectors and the pool vectors (after the generation: (CurrentListFileName) stores the current system vectors id, (ReserveListFileName) stores the pool vectors id, (NewDataSetFileName) stores the vectors of current system vectors) --> generate groundTruth based on the system vectors after applying the trace --> convert groundTruth IDs from local to global (using the (CurrentListFileName) to remap the id in groundTruth)

Apologize for the bad scripts and thank you for your patience on evaluating this repo:)

**Comment by Funlxy** [comment]
> Oh we did forget to add those parameters in the shell script since we didn't fully test the generation script in this AE repo (we use other scripts in our experiments to generate data and we try to merge code within the repo during AE) :(
> 
> Your analysis is correct and we will fix this script as soon as possible.
> 
> If you are in a hurry, I suggest you to fix this script in yourself, the logic is easy:
> 
> Generate trace based on the current system vectors and the pool vectors (after the generation: (CurrentListFileName) stores the current system vectors id, (ReserveListFileName) stores the pool vectors id, (NewDataSetFileName) stores the vectors of current system vectors) --> generate groundTruth based on the system vectors after applying the trace --> convert groundTruth IDs from local to global (using the (CurrentListFileName) to remap the id in groundTruth)
> 
> Apologize for the bad scripts and thank you for your patience on evaluating this repo:)

Thank you for your reply！
