### ISSUE TITLE
Errors Encountered During the CMake Compilation Process

### ISSUE THREAD

**Issue by Mysshuaige** [SPFresh/SPFresh#6]
Hello, I always encounter the following errors during the process of creating a Docker image using a Dockerfile, and I face the same errors even after installing RocksDB. May I ask if there is a way to avoid using RocksDB or if there is a solution to fix this bug?
<img width="662" alt="微信图片_20240108073131" src="https://github.com/SPFresh/SPFresh/assets/137894571/a0b3b491-c22a-4991-8f63-31adc4f0a78b">

**Comment by Yuming-Xu** [comment]
Hello, this error is caused by RocksDB missing, the code to find the RocksDB dependency is in AnnService/CMakeList: 47, I think you can try to figure out why **find_package(RocksDB CONFIG)** didn't work in the Docker:)
Not that we test SPFresh on the physical machine and Azure virtual machine instead of inside a Docker, there maybe something different in the docker environment:)
